"""user_id_sync

Revision ID: 8c7ccd6960fd
Revises: c45651c735ff
Create Date: 2026-05-28 00:36:25.653234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7ccd6960fd'
down_revision: Union[str, Sequence[str], None] = 'c45651c735ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_operations', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sync_operations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_operations', type_='foreignkey')
    op.drop_column('sync_operations', 'user_id')
    # ### end Alembic commands ###
