"""add default 0 to funds

Revision ID: 952d410967cd
Revises: 0e4efb317ab4
Create Date: 2026-05-04 18:13:46.998548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952d410967cd'
down_revision: Union[str, Sequence[str], None] = '0e4efb317ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'accounts', 
        'funds',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        server_default='0',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'accounts', 
        'funds',
        existing_type=sa.NUMERIC(precision=10, scale=2),
        server_default=None,
        nullable=True
    )
    # ### end Alembic commands ###
