"""add_email_codes_table

Revision ID: 9a216b827d74
Revises: f8980dc39330
Create Date: 2026-03-19 22:16:36.528528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a216b827d74'
down_revision: Union[str, Sequence[str], None] = 'f8980dc39330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_codes',
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('change_password', 'change_email', 'register', name='emailcodeaction'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_email_codes_code_hash'), 'email_codes', ['code_hash'], unique=False)
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'operations', ['id'])
    op.create_unique_constraint(None, 'sync_operations', ['id'])
    op.create_unique_constraint(None, 'transfers', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transfers', type_='unique')
    op.drop_constraint(None, 'sync_operations', type_='unique')
    op.drop_constraint(None, 'operations', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_index(op.f('ix_email_codes_code_hash'), table_name='email_codes')
    op.drop_table('email_codes')
    # ### end Alembic commands ###
