"""

Revision ID: b8c7b02479cf
Revises: 84e613ba68bf
Create Date: 2026-03-27 14:01:37.427807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c7b02479cf'
down_revision: Union[str, Sequence[str], None] = '84e613ba68bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('color', sa.String(), nullable=False))
    op.add_column('operations', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'operations', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'category_id')
    op.drop_column('accounts', 'color')
    # ### end Alembic commands ###
