"""add type to category

Revision ID: c45651c735ff
Revises: 952d410967cd
Create Date: 2026-05-05 20:54:56.184812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45651c735ff'
down_revision: Union[str, Sequence[str], None] = '952d410967cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE categorytype AS ENUM('INCOME', 'OUTCOME')")
    op.add_column('categories', sa.Column('type', sa.Enum('INCOME', 'OUTCOME', name='categorytype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
