"""soft_delete

Revision ID: d6c477652c02
Revises: fee17f6faa28
Create Date: 2026-05-03 22:50:34.331759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c477652c02'
down_revision: Union[str, Sequence[str], None] = 'fee17f6faa28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('operations', sa.Column('category_uuid', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('operations_category_id_fkey'), 'operations', type_='foreignkey')
    op.create_foreign_key("fk_category_operation", 'operations', 'categories', ['category_uuid'], ['id'])
    op.drop_column('operations', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint("fk_category_operation", 'operations', type_='foreignkey')
    op.create_foreign_key(op.f('operations_category_id_fkey'), 'operations', 'categories', ['category_id'], ['id'])
    op.drop_column('operations', 'category_uuid')
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
