"""add emoji to category

Revision ID: d8bbd6440d79
Revises: d6c477652c02
Create Date: 2026-05-03 23:13:07.614254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bbd6440d79'
down_revision: Union[str, Sequence[str], None] = 'd6c477652c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('emoji', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'emoji')
    # ### end Alembic commands ###
