"""add_fields_values_sync_op

Revision ID: fee17f6faa28
Revises: 2201c52ea27d
Create Date: 2026-04-16 16:15:03.913712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fee17f6faa28'
down_revision: Union[str, Sequence[str], None] = '2201c52ea27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_operations', sa.Column('field_to_update', sa.String(length=100), nullable=True))
    op.add_column('sync_operations', sa.Column('value_to_update', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_processing_id', 'sync_operations', ['processing_id'], unique=False)
    op.create_index('idx_sync_created_at', 'sync_operations', ['created_at'], unique=False)
    op.create_index('idx_sync_proc_id_date', 'sync_operations', ['processing_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sync_proc_id_date', table_name='sync_operations')
    op.drop_index('idx_sync_created_at', table_name='sync_operations')
    op.drop_index('idx_processing_id', table_name='sync_operations')
    op.drop_column('sync_operations', 'value_to_update')
    op.drop_column('sync_operations', 'field_to_update')
    # ### end Alembic commands ###
